[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hexai_pdf_parser"
dynamic = ["version"]
description = "A Python library for parsing PDF layouts"
requires-python = ">=3.7"
dependencies = [
    "PyMuPDF",
]

[project.optional-dependencies]
ml = [
    "onnxruntime>=1.8.0",
    "numpy>=1.20.0",
    "opencv-python>=4.2.0",
]
dev = [
    "pytest>=7.0",
]

[project.scripts]
hexai_pdf_parser = "hexai_pdf_parser.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.dynamic]
version = {file = "version"}

[tool.setuptools.package-data]
"hexai_pdf_parser.tables" = ["table_templates/*.json"]
"hexai_pdf_parser.ml" = ["table_detector_model/*.onnx"]

[tool.pytest.ini_options]
addopts = "-p no:cacheprovider"
